apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  annotations:
  {{- if .Values.ingress.annotations }}
  {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.hasIssuerAnnotation }}
  {{- range $key, $value := .Values.ingress.tls.issuerAnnotation }}
      {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-{{ .Release.Name }}
                port:
                  number: 8080
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: tls-ingress-{{ .Release.Name }}